trigger:
  - main
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'  # Directly specify Python 3.8

  - script: |
      python -m pip install --upgrade pip
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    displayName: 'Install Dependencies'

  - script: python sum.py
    displayName: 'Run Python Script'

  - script: |
      echo "This is Section 1 Azure Demonstration"
      echo "KL-CSE"
    displayName: 'Inline Python Execution'
