name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest available runner

    strategy:
      matrix:
        python-version: [3.8]  # Updated to Python 3.8

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python Script
        run: python add.py  # Ensure sum.py is compatible with Python 3

      - name: Inline Python Execution
        run: |
          echo "This is Section 1 Azure Demonstration"
          echo "KL-CSE"
